import './App.css';
import Sidebar from './components/sidebar';
import Home from './pages/Home/';
import About from './pages/About/';

function App() {
  return (
    <div className="app-container">
      <Sidebar />
      <main className="page-wrapper">
        <section id="home">
          <Home/>
        </section>
        <section id="about">
          <About/>
        </section>
        <section id="projects">
          <h2>PROJECTS</h2>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
        </section>
        <section id="tutoring">
          <h2>TUTORING</h2>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
          <p>Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb.Hello! I’m Nirav, a DataSci student at UniMelb. </p>
        </section>
      </main>
    </div>
  );
}


export default App;